quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/finance

  # drop and crate option only for developing
  # none : nice to check if mapping is okay if it matches with your sql scheme
  hibernate-orm:
    database:
      generation: none